Add archive function

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -698,3 +698,73 @@ lno() {
   fi
 }
 
+#
+# Archive
+#
+
+archive() {
+
+  # Usage.
+  if [[ $# -lt 2 ]]; then
+
+cat <<-'EOF'
+  Usage: $0
+    archive destination.extension source
+EOF
+
+    return 1
+  fi
+
+  # Error if destination already exists.
+  if [[ -f "$1" ]]; then
+    echo "[ERROR]: $1 already exists."
+
+    return 1
+  fi
+
+  local file
+
+  # Lowercase filename for case matching.
+  file="${(L)1}"
+
+  case "${file}" in
+    *.7z )
+      7za a -t7z -mmt "$@"
+      ;;
+    *.bz2 )
+      7za a -tbzip2 "$@"
+      ;;
+    *.gz )
+      7za a -tgzip "$@"
+      ;;
+    *.tar.bz2 )
+      tar -cvjf "$@"
+      ;;
+    *.tar.gz )
+      tar -cvzf "$@"
+      ;;
+    *.tar.lzma )
+      tar --lzma -cvf "$@"
+      ;;
+    *.tar.xz )
+      tar -cvJf "$@"
+      ;;
+    *.tar )
+      tar -cvf "$@"
+      ;;
+    *.tbz2 )
+      tar -cvjf "$@"
+      ;;
+    *.tgz )
+      tar -cvzf "$@"
+      ;;
+    *.zip )
+      zip -r "$@"
+      ;;
+    * )
+      echo "${file} has an unknown file extension."
+      exit 1
+      ;;
+  esac
+}
+
